### ISSUE TITLE
multiple plants being carried

### ISSUE THREAD

**Issue by nickversusspam** [jordanpinski/RPG_GAME#2]
the carry state works fine until two pots get close and you go to pick one up. one gets deleted.
we need a for loop with arguments and a way to check for specific ids of instances of the same object.

**Comment by jordanpinski** [comment]
Okay, I'll take a look at it today. You should post in issue on our Github
instead of emailing me so everybody can see it.

**Comment by jordanpinski** [comment]
ah shit. cool

**Comment by jordanpinski** [comment]
This should be fixed with the last commit. Check to see if it's what you want.
